# Generated by Django 3.1.7 on 2021-03-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_expiring_token', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringtoken',
            name='expires',
            field=models.DateTimeField(db_index=True, verbose_name='Expires in'),
        ),
    ]
